### ISSUE TITLE
Crash when viewing macOS address book database table `MODELCACHE`

### ISSUE THREAD

**Issue by davep** [cdelker/sqliteview#1]
Having seen you mention it [over in the fediverse](https://fosstodon.org/@codeismycanvas@universeodon.com/110030659286494925) I thought I'd take this for a spin. Looks great! Not really being much of a user of SQLite I needed any database quick to view so I thought I'd dive into the Apple address book data.

If I try and view the table `MODELCACHE` I get a crash deep in the guts of Rich, down in `markup.py`, showing a `MarkupError: closing tag ... at position 111721 doesn't match any open tag` (where `...` in there is a load of binary data).

It's possible that this is a Rich issue, or perhaps a Textual `DataTable` issue, but I wanted to flag it up for you first in case it's more a case of needing to be defensive about some kinds of data pulled from the database (in this case it's some unholy binary blob by the looks of things -- I would post the full information here but I'm not even sure if it might include sensitive data or not; hence the more vague report to start with).

Happy to move this over to the Textual issues if we feel that the `DataTable` might need to be a bit more defensive about content that might cause errors.

**Comment by cdelker** [comment]
Thanks for this - it's definitely something I should handle gracefully. Check the data type of the column, and if it's a binary blob type, let the user can see there's data, but not try to show it or allow editing. Or maybe trying to edit a binary field could just ask to load the data from a file.

Not sure if you want to harden `DataTable` too, but it could be nice if it threw a more descriptive error message when it gets unexpected content.

**Comment by cdelker** [comment]
On further investigation, the specific error is raised because `DataTable` is trying to render rich content in the cell - it encountered a string it interpreted as a closing format tag, something like `[/bold]`, but didn't see an opening tag. Inevitably, the `[/***]` pattern just happened to show up in several kilobytes of binary image data converted to a string that I threw in there.

@davep , is there a way to disable Rich rendering in the `DataTable`? I should still fix it to not try to show a bunch of binary gunk, but that would prevent the crash at least.

**Comment by davep** [comment]
@cdelker Off the top of my head I don't know of a way of turning off RIch rendering in the table, and thinking about it at the moment I can see how this could possibly be a source of some issues -- I might have to bring that up with Will and Darren and see what they think (in part Textual is about building on top of Rich so supporting that "out of the box" is going to be really useful for most folk, so having it "just work" by default feels like the right thing to do).

Perhaps the best thing for your app is sanitise the data being fed to the `DataTable` using [`rich.markup.escape`](https://rich.readthedocs.io/en/stable/reference/markup.html?highlight=escape#rich.markup.escape)?

**Comment by cdelker** [comment]
@davep Escape is exactly what I need - that's the disable feature I'm looking for. With that, I don't think anything needs to change on your end. Thanks for the comments and a great package!

**Comment by davep** [comment]
My pleasure. And thanks for working with Textual. Looking forward to seeing how this application grows. 

Also reminded me I should use SQLite for some stuff.
